stages:
  - test
  - publish

test:
  stage: test
  image: source.donesky.dev:4567/donesky/docker/java:12
  tags:
    - docker
  script:
    - ./gradlew --no-daemon check codeCoverageReport
    - cat build/reports/jacoco/codeCoverageReport/html/index.html | grep -o '<tfoot>.*</tfoot>'

publish:
  stage: publish
  image: source.donesky.dev:4567/donesky/docker/java:12
  tags:
    - docker
  script:
    - ./gradlew --no-daemon clean publish
